/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a one-use fragment bootstrap token for a viewer session. */
        post: operations["exchangeViewerBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bounded persisted endpoint observations.
         * @description Lists only persisted observations accepted under the finite spring-orders-v1 operator-selected policy. The policy does not attest which adapter or application produced the event, and this endpoint does not claim framework handler discovery or catalog completeness.
         */
        get: operations["listObservedEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/endpoints/{operationId}/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recordings explicitly linked to one observed operation. */
        get: operations["listOperationRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["showRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            /** @constant */
            authenticated: true;
            /** Format: uuid */
            requestId: string;
        };
        RecordingList: {
            /** @constant */
            schemaVersion: 1;
            /** Format: uuid */
            projectId: string;
            limit: number;
            /** Format: uuid */
            after: string | null;
            /** Format: uuid */
            nextAfter: string | null;
            recordings: components["schemas"]["Recording"][];
            unavailable: components["schemas"]["Unavailable"];
            /** Format: uuid */
            requestId: string;
        };
        Recording: {
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            /** Format: date-time */
            openedAt: string;
            segmentCount: string;
            eventCount: string;
            firstSequence?: string | null;
            lastSequence?: string | null;
            incompleteEvidence: string[];
        };
        ObservedEndpointPage: {
            items: components["schemas"]["ObservedEndpoint"][];
            nextCursor: string | null;
        };
        ObservedEndpoint: {
            /** Format: uuid */
            operationId: string;
            /** Format: uuid */
            projectId: string;
            /** @constant */
            applicationComponent: "spring-fixture";
            /** @constant */
            binding: "default";
            /** @constant */
            method: "POST";
            /** @constant */
            routeTemplate: "/orders";
            /** @constant */
            observation: "observed";
            /**
             * @description Operator-selected policy; it does not attest the adapter or application.
             * @constant
             */
            observationPolicy: "spring-orders-v1";
        };
        ObservedRecordingPage: {
            items: components["schemas"]["ObservedRecording"][];
            nextCursor: string | null;
        };
        ObservedRecording: {
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            /** Format: date-time */
            openedAt: string;
            segmentCount: string;
            eventCount: string;
            firstSequence: string | null;
            lastSequence: string | null;
            incompleteEvidence: string[];
            /** Format: uuid */
            operationId: string | null;
            /** @enum {string|null} */
            observationPolicy: "spring-orders-v1" | null;
            /** @enum {string|null} */
            unmatchedReason: "observation_policy_missing" | "observation_policy_invalid" | "identity_context_missing" | "identity_context_invalid" | "method_unsupported" | "route_unapproved" | null;
        };
        RecordingDetail: {
            /** @constant */
            schemaVersion: 1;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            limit: number;
            cursor: string | null;
            nextCursor: string | null;
            segmentCount: string;
            events: components["schemas"]["Event"][];
            incompleteEvidence: string[];
            unavailable: components["schemas"]["Unavailable"];
            /** Format: uuid */
            requestId: string;
        };
        Event: {
            sequence: string;
            monotonicNs: string;
            eventId?: string | null;
            parentEventId?: string | null;
            asyncParentEventId?: string | null;
            kind: string;
            symbol?: string | null;
            interaction?: {
                [key: string]: string | null;
            } | null;
            /**
             * @description Adapter-reported compile-time class-to-source binding result.
             * @enum {string}
             */
            sourceBinding: "unspecified" | "verified" | "attestation_missing" | "class_bytes_mismatch" | "debug_metadata_absent" | "source_metadata_invalid";
            source?: null | {
                path: string;
                /** @description Lower bound of the fixture method debug-line extent, not an active execution cursor. */
                startLine: number;
                /** @description Inclusive upper bound of the fixture method debug-line extent, when available. */
                endLine: number | null;
                /** @enum {string} */
                status: "matched" | "mismatch" | "unavailable";
                excerpt: string | null;
                truncated: boolean;
            };
            fieldTruncations: {
                field: string;
                originalBytes: string;
                /** @enum {string} */
                representation: "truncated" | "unavailable";
            }[];
        };
        Unavailable: {
            /** @constant */
            source: "unavailable";
            /** @constant */
            values: "unavailable";
            /** @constant */
            completion: "unavailable";
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail: string;
            code: string;
            /** Format: uuid */
            requestId: string;
        };
    };
    responses: {
        /** @description Safe RFC 9457-like problem document. */
        Problem: {
            headers: {
                /** @description Correlation ID included in the problem body. */
                "X-XTrace-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
        ViewerHost: string;
        /** @description Must be exactly same-origin. */
        ViewerFetchSite: "same-origin";
        /** @description Required browser-client marker; must be exactly viewer-v1. */
        ViewerClient: "viewer-v1";
        /** @description Must exactly equal the printed viewer origin, including port. */
        ExchangeOrigin: string;
        /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
        OptionalApiOrigin: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeViewerBootstrap: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description Must exactly equal the printed viewer origin, including port. */
                Origin: components["parameters"]["ExchangeOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Unpadded base64url encoding of exactly 32 CSPRNG bytes. The token is delivered in the URL fragment and consumed once within 60 seconds. */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Authenticated. Sets a host-only HttpOnly SameSite=Strict browser-session cookie with no persistence attributes. The server enforces a 15-minute session lifetime. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    listRecordings: {
        parameters: {
            query?: {
                /** @description Legacy mode (unmatched absent): default 50, maximum 200. Observed unmatched mode (unmatched=true): default 25, maximum 50. Values outside the active mode's bounds are rejected. */
                limit?: number;
                /** @description Exclusive stable legacy recording identity cursor. Accepted only when unmatched is absent. */
                after?: string;
                /** @description When exactly true, selects the observed unmatched-recording projection, including legacy sidecar-absent recordings. When absent, the legacy recordings response and after cursor remain unchanged. Other values are rejected. This is an observed projection, not a complete endpoint catalog. */
                unmatched?: true;
                /** @description Opaque shared application cursor. Accepted only with unmatched=true; cannot be combined with after. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description With unmatched absent, returns the unchanged legacy page. With unmatched=true, returns the shared observed-recording page in stable descending openedAt and recordingId order. */
            200: {
                headers: {
                    /** @description Correlation ID shared with safe problem responses. */
                    "X-XTrace-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingList"] | components["schemas"]["ObservedRecordingPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listObservedEndpoints: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Shared canonical query and project-bound continuation cursor. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direct shared application page with no transport wrapper. */
            200: {
                headers: {
                    /** @description Correlation ID shared with safe problem responses. */
                    "X-XTrace-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservedEndpointPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listOperationRecordings: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Shared project and operation bound continuation cursor. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                /** @description Canonical lowercase RFC UUIDv7 public operation identity. */
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direct shared application page of linked recordings. */
            200: {
                headers: {
                    /** @description Correlation ID shared with safe problem responses. */
                    "X-XTrace-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservedRecordingPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    showRecording: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque project and recording scoped versioned continuation token. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded ordered event projection backed by verified XTF segments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
