/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a one-use fragment bootstrap token for a viewer session. */
        post: operations["exchangeViewerBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["showRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            /** @constant */
            authenticated: true;
            /** Format: uuid */
            requestId: string;
        };
        RecordingList: {
            /** @constant */
            schemaVersion: 1;
            /** Format: uuid */
            projectId: string;
            limit: number;
            /** Format: uuid */
            after: string | null;
            /** Format: uuid */
            nextAfter: string | null;
            recordings: components["schemas"]["Recording"][];
            unavailable: components["schemas"]["Unavailable"];
            /** Format: uuid */
            requestId: string;
        };
        Recording: {
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            /** Format: date-time */
            openedAt: string;
            segmentCount: string;
            eventCount: string;
            firstSequence?: string | null;
            lastSequence?: string | null;
            incompleteEvidence: string[];
        };
        RecordingDetail: {
            /** @constant */
            schemaVersion: 1;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            limit: number;
            cursor: string | null;
            nextCursor: string | null;
            segmentCount: string;
            events: components["schemas"]["Event"][];
            incompleteEvidence: string[];
            unavailable: components["schemas"]["Unavailable"];
            /** Format: uuid */
            requestId: string;
        };
        Event: {
            sequence: string;
            monotonicNs: string;
            eventId?: string | null;
            parentEventId?: string | null;
            asyncParentEventId?: string | null;
            kind: string;
            symbol?: string | null;
            interaction?: {
                [key: string]: string | null;
            } | null;
            fieldTruncations: {
                field: string;
                originalBytes: string;
                /** @enum {string} */
                representation: "truncated" | "unavailable";
            }[];
        };
        Unavailable: {
            /** @constant */
            source: "unavailable";
            /** @constant */
            values: "unavailable";
            /** @constant */
            completion: "unavailable";
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail: string;
            code: string;
            /** Format: uuid */
            requestId: string;
        };
    };
    responses: {
        /** @description Safe RFC 9457-like problem document. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
        ViewerHost: string;
        /** @description Must be exactly same-origin. */
        ViewerFetchSite: "same-origin";
        /** @description Required browser-client marker; must be exactly viewer-v1. */
        ViewerClient: "viewer-v1";
        /** @description Must exactly equal the printed viewer origin, including port. */
        ExchangeOrigin: string;
        /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
        OptionalApiOrigin: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeViewerBootstrap: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description Must exactly equal the printed viewer origin, including port. */
                Origin: components["parameters"]["ExchangeOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Unpadded base64url encoding of exactly 32 CSPRNG bytes. The token is delivered in the URL fragment and consumed once within 60 seconds. */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Authenticated. Sets a host-only HttpOnly SameSite=Strict browser-session cookie with no persistence attributes. The server enforces a 15-minute session lifetime. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    listRecordings: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Exclusive stable recording identity cursor. */
                after?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded metadata-only page in deterministic order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    showRecording: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque project and recording scoped versioned continuation token. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded ordered event projection backed by verified XTF segments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
