/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a one-use fragment bootstrap token for a viewer session. */
        post: operations["exchangeViewerBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bounded persisted endpoint observations.
         * @description Lists only persisted observations accepted under the finite spring-orders-v1 operator-selected policy. The policy does not attest which adapter or application produced the event, and this endpoint does not claim framework handler discovery or catalog completeness.
         */
        get: operations["listObservedEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/endpoints/{operationId}/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recordings explicitly linked to one observed operation. */
        get: operations["listOperationRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["showRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}/frames/{frameId}/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All navigation actions of one frame in a single call. */
        get: operations["showFrameNavigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}/navigate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Resolve one navigation action from a frame (action). The kinds filter and the gap, error or interaction jump (kind and dir) are registered and answer 501 XTR-REPLAY-NOT-IMPLEMENTED until served. */
        get: operations["navigateRecording"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Window of frames by ordinal under the structure or full projection. */
        get: operations["listRecordingFrames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recordingId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Async and frame graph derived from structure rows. */
        get: operations["showRecordingGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponse: {
            /** @constant */
            authenticated: true;
            /** Format: uuid */
            requestId: string;
        };
        RecordingList: {
            /** @constant */
            schemaVersion: 3;
            /** Format: uuid */
            projectId: string;
            limit: number;
            /** Format: uuid */
            after: string | null;
            /** Format: uuid */
            nextAfter: string | null;
            recordings: components["schemas"]["Recording"][];
            unavailable: components["schemas"]["Unavailable"];
            /** Format: uuid */
            requestId: string;
        };
        Recording: {
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            completion: components["schemas"]["Completion"];
            /** Format: date-time */
            openedAt: string;
            segmentCount: string;
            eventCount: string;
            firstSequence?: string | null;
            lastSequence?: string | null;
            incompleteEvidence: string[];
            /** @description Event cap recorded in terminal evidence. */
            eventCap?: number | null;
            /**
             * @description Outcome kind from terminal evidence; null when no terminal evidence exists.
             * @enum {string|null}
             */
            outcomeKind?: "responded" | "exception_propagated" | "client_aborted" | "unobserved" | null;
        };
        ObservedEndpointPage: {
            items: components["schemas"]["ObservedEndpoint"][];
            nextCursor: string | null;
        };
        ObservedEndpoint: {
            /** Format: uuid */
            operationId: string;
            /** Format: uuid */
            projectId: string;
            /** @constant */
            applicationComponent: "spring-fixture";
            /** @constant */
            binding: "default";
            /** @constant */
            method: "POST";
            /** @constant */
            routeTemplate: "/orders";
            /** @constant */
            observation: "observed";
            /**
             * @description Operator-selected policy; it does not attest the adapter or application.
             * @constant
             */
            observationPolicy: "spring-orders-v1";
        };
        ObservedRecordingPage: {
            items: components["schemas"]["ObservedRecording"][];
            nextCursor: string | null;
        };
        ObservedRecording: {
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            completion: components["schemas"]["Completion"];
            /** Format: date-time */
            openedAt: string;
            segmentCount: string;
            eventCount: string;
            firstSequence: string | null;
            lastSequence: string | null;
            incompleteEvidence: string[];
            /** Format: uuid */
            operationId: string | null;
            /** @enum {string|null} */
            observationPolicy: "spring-orders-v1" | null;
            /** @enum {string|null} */
            unmatchedReason: "observation_policy_missing" | "observation_policy_invalid" | "identity_context_missing" | "identity_context_invalid" | "method_unsupported" | "route_unapproved" | null;
        };
        RecordingDetail: {
            /** @constant */
            schemaVersion: 3;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            recordingId: string;
            /** @enum {string} */
            status: "recording" | "finalizing" | "complete" | "partial" | "invalid";
            completion: components["schemas"]["Completion"];
            /** @description Producer-declared privacy-safe summary; it is not independently correlated to a RESPONSE event and is not outcome proof. */
            adapterSummary: null | components["schemas"]["AdapterSummary"];
            durationNs: string | null;
            dropCountsByPriority: {
                [key: string]: string;
            };
            limit: number;
            cursor: string | null;
            nextCursor: string | null;
            segmentCount: string;
            events: components["schemas"]["Event"][];
            incompleteEvidence: string[];
            unavailable: components["schemas"]["Unavailable"];
            /** @description Adapter-observed outcome; null when terminal evidence is absent. Nothing is synthesized. */
            outcome: null | components["schemas"]["Outcome"];
            /** @description Event capacity facts; null when terminal evidence is absent. */
            capacity: null | components["schemas"]["Capacity"];
            /** @description Stable limitation codes, for example capture_policy_not_armed. */
            limitations: string[];
            honesty: components["schemas"]["Honesty"];
            /** Format: uuid */
            anchorFrameId: string | null;
            firstSequence: string | null;
            lastSequence: string | null;
            prevCursor: string | null;
            /** @enum {string} */
            projection: "full" | "structure";
            /** Format: uuid */
            requestId: string;
        };
        Outcome: {
            /** @enum {string} */
            kind: "responded" | "exception_propagated" | "client_aborted" | "unobserved";
            httpStatus: number | null;
            exception: null | {
                exceptionType: string;
                message: string | null;
            };
            thrownFromEventId: string | null;
        };
        Capacity: {
            eventCap: number;
            eventCount: number;
            capacityDroppedEvents: string;
            dropsByPriority: {
                [key: string]: string;
            };
        };
        Honesty: {
            /** @constant */
            schemaVersion: 1;
            recording: {
                completion: components["schemas"]["Completion"];
                incomplete: string[];
                capacityDroppedEvents: string;
                dropsByPriority: {
                    [key: string]: string;
                };
                framesWithGap: number | null;
                framesWithRedacted: number | null;
                framesWithTruncated: number | null;
                framesWithUnavailable: number | null;
                framesWithDropped: number | null;
                framesWithOrphanParent: number | null;
                /** @description False when frame counts cannot be computed; counts are then null, never zero. */
                countsAvailable: boolean;
            };
            window: {
                events: number;
                bindingsByState: {
                    [key: string]: number;
                };
                unavailableByReason: {
                    [key: string]: number;
                };
                droppedByReason: {
                    [key: string]: number;
                };
                gaps: {
                    sequence: string;
                    reason: string;
                    count: string;
                    firstSequence: string;
                    lastSequence: string;
                }[];
                sourceBindings: {
                    [key: string]: number;
                };
                sourceStatus: {
                    [key: string]: number;
                };
            };
        };
        Binding: {
            name: string;
            role: string;
            nameOrigin: string;
            value: {
                /** @constant */
                state: "captured";
                shape: string;
                preview: string;
                contentHash: string;
            } | {
                /** @constant */
                state: "redacted";
                ruleId: string;
                shapeHint: string | null;
            } | {
                /** @constant */
                state: "truncated";
                preview: string;
                originalSizeLowerBound: string;
                limit: string;
            } | {
                /** @constant */
                state: "unavailable";
                reason: string;
            } | {
                /** @constant */
                state: "dropped";
                reason: string;
            };
        };
        /** @description Suppressed observations never receive a sequence. firstSequence and lastSequence bracket the nearest emitted events; count is the number suppressed and may exceed their distance. */
        Gap: {
            reason: string;
            count: string;
            firstSequence: string;
            lastSequence: string;
        };
        FrameNavigationDocument: {
            /** Format: uuid */
            frameId: string;
            sequence: string;
            depth: number | null;
            /** Format: uuid */
            parentFrameId: string | null;
            navigation: components["schemas"]["FrameNavigation"];
            /** Format: uuid */
            requestId?: string;
        };
        NavigateDocument: {
            /** Format: uuid */
            frameId: string;
            /** @enum {string} */
            action?: "previous" | "next" | "into" | "over" | "out";
            result: components["schemas"]["NavigationResult"];
            /** Format: uuid */
            requestId?: string;
        };
        RecordingGraph: {
            nodes: {
                /** Format: uuid */
                frameId: string;
                kind: string;
                depth: number | null;
                count?: number;
            }[];
            edges: {
                /** Format: uuid */
                from: string;
                /** Format: uuid */
                to: string;
                /** @enum {string} */
                relation: "parent" | "async_parent";
            }[];
        };
        Event: {
            sequence: string;
            /** Format: uuid */
            frameId: string | null;
            navigation: components["schemas"]["FrameNavigation"];
            monotonicNs: string;
            eventId?: string | null;
            parentEventId?: string | null;
            asyncParentEventId?: string | null;
            kind: string;
            symbol?: string | null;
            interaction?: {
                [key: string]: string | null;
            } | null;
            /**
             * @description Adapter-reported compile-time class-to-source binding result.
             * @enum {string}
             */
            sourceBinding: "unspecified" | "verified" | "attestation_missing" | "class_bytes_mismatch" | "debug_metadata_absent" | "source_metadata_invalid" | "observed_unattested" | "source_map_absent" | "source_map_unresolved";
            source?: null | {
                path: string;
                /** @description Lower bound of the fixture method debug-line extent, not an active execution cursor. */
                startLine: number;
                /** @description Inclusive upper bound of the fixture method debug-line extent, when available. */
                endLine: number | null;
                /** @enum {string} */
                status: "matched" | "mismatch" | "unavailable" | "missing_file";
                excerpt: string | null;
                truncated: boolean;
            };
            fieldTruncations: {
                field: string;
                originalBytes: string;
                /** @enum {string} */
                representation: "truncated" | "unavailable";
            }[];
            /** @description Null for legacy or unindexed rows. */
            depth: number | null;
            /**
             * Format: uuid
             * @description Only when the parent was observed.
             */
            parentFrameId: string | null;
            /**
             * Format: uuid
             * @description Only when the async parent was observed.
             */
            asyncParentFrameId: string | null;
            /** @description Observed line; set only for line_cursor events and never a method extent. */
            line: number | null;
            /** @description Empty means none observed. */
            bindings: components["schemas"]["Binding"][];
            gap: null | components["schemas"]["Gap"];
        };
        /** @enum {string} */
        Completion: "complete" | "partial" | "invalid" | "unavailable";
        FrameNavigation: {
            previous: components["schemas"]["NavigationResult"];
            next: components["schemas"]["NavigationResult"];
            into: components["schemas"]["NavigationResult"];
            over: components["schemas"]["NavigationResult"];
            out: components["schemas"]["NavigationResult"];
        };
        NavigationResult: {
            /** @constant */
            state: "target";
            /** Format: uuid */
            frameId: string;
        } | {
            /** @constant */
            state: "boundary";
        } | {
            /** @constant */
            state: "unavailable";
            /** @enum {string} */
            reason: "partial_frontier" | "legacy_unindexed" | "depth_overflow" | "orphan_parent" | "not_navigable";
        };
        /** @description No preview text or producer-supplied rule identifier is exposed until a verified policy registry exists. */
        AdapterSummary: {
            Redacted: {
                /** @constant */
                rule_id: "unverified-producer-redaction";
                shape_hint: unknown;
            };
        } | {
            Unavailable: {
                /** @enum {string} */
                reason: "capability_unsupported" | "debug_metadata_absent" | "capture_budget_exhausted" | "source_artifact_missing" | "recorder_disconnected" | "privacy_policy_unavailable";
            };
        } | {
            Dropped: {
                /** @enum {string} */
                reason: "backpressure_shed" | "queue_full" | "sequence_gap" | "adapter_dropped";
            };
        };
        Unavailable: {
            /** @enum {string} */
            source: "unavailable" | "available";
            /** @enum {string} */
            values: "unavailable" | "available";
            /** @enum {string} */
            completion: "available" | "unavailable" | "per_recording";
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail: string;
            code: string;
            /** Format: uuid */
            requestId: string;
        };
    };
    responses: {
        /** @description Safe RFC 9457-like problem document. */
        Problem: {
            headers: {
                /** @description Correlation ID included in the problem body. */
                "X-XTrace-Request-Id"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
        ViewerHost: string;
        /** @description Must be exactly same-origin. */
        ViewerFetchSite: "same-origin";
        /** @description Required browser-client marker; must be exactly viewer-v1. */
        ViewerClient: "viewer-v1";
        /** @description Must exactly equal the printed viewer origin, including port. */
        ExchangeOrigin: string;
        /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
        OptionalApiOrigin: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    exchangeViewerBootstrap: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description Must exactly equal the printed viewer origin, including port. */
                Origin: components["parameters"]["ExchangeOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Unpadded base64url encoding of exactly 32 CSPRNG bytes. The token is delivered in the URL fragment and consumed once within 60 seconds. */
                    token: string;
                };
            };
        };
        responses: {
            /** @description Authenticated. Sets a host-only HttpOnly SameSite=Strict browser-session cookie with no persistence attributes. The server enforces a 15-minute session lifetime. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    listRecordings: {
        parameters: {
            query?: {
                /** @description Legacy mode (unmatched absent): default 50, maximum 200. Observed unmatched mode (unmatched=true): default 25, maximum 50. Values outside the active mode's bounds are rejected. */
                limit?: number;
                /** @description Exclusive stable legacy recording identity cursor. Accepted only when unmatched is absent. */
                after?: string;
                /** @description When exactly true, selects the observed unmatched-recording projection, including legacy sidecar-absent recordings. When absent, the legacy recordings response and after cursor remain unchanged. Other values are rejected. This is an observed projection, not a complete endpoint catalog. */
                unmatched?: true;
                /** @description Opaque shared application cursor. Accepted only with unmatched=true; cannot be combined with after. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description With unmatched absent, returns the unchanged legacy page. With unmatched=true, returns the shared observed-recording page in stable descending openedAt and recordingId order. */
            200: {
                headers: {
                    /** @description Correlation ID shared with safe problem responses. */
                    "X-XTrace-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingList"] | components["schemas"]["ObservedRecordingPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listObservedEndpoints: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Shared canonical query and project-bound continuation cursor. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direct shared application page with no transport wrapper. */
            200: {
                headers: {
                    /** @description Correlation ID shared with safe problem responses. */
                    "X-XTrace-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservedEndpointPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listOperationRecordings: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Shared project and operation bound continuation cursor. */
                cursor?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                /** @description Canonical lowercase RFC UUIDv7 public operation identity. */
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Direct shared application page of linked recordings. */
            200: {
                headers: {
                    /** @description Correlation ID shared with safe problem responses. */
                    "X-XTrace-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservedRecordingPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    showRecording: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque project and recording scoped versioned continuation token. */
                cursor?: string;
                /** @description Window of limit events centred on this frame. Mutually exclusive with cursor. A frame that is not in this recording answers 404. */
                aroundFrame?: string;
                /** @description full (default) returns every event field; structure returns outline fields only. structure answers 501 XTR-REPLAY-NOT-IMPLEMENTED until served. */
                projection?: "full" | "structure";
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded ordered event projection backed by verified XTF segments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
            501: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    showFrameNavigation: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                recordingId: string;
                frameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Navigation facts for the frame. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameNavigationDocument"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            501: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    navigateRecording: {
        parameters: {
            query: {
                frame: string;
                action?: "previous" | "next" | "into" | "over" | "out";
                /** @description Comma separated event kinds applied to previous and next. */
                kinds?: string;
                kind?: "gap" | "error" | "interaction";
                dir?: "next" | "previous";
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result of the requested navigation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigateDocument"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            501: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    listRecordingFrames: {
        parameters: {
            query?: {
                fromOrdinal?: number;
                limit?: number;
                kinds?: string;
            };
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frame window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            501: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    showRecordingGraph: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact 127.0.0.1 authority, including the viewer's assigned port. */
                Host: components["parameters"]["ViewerHost"];
                /** @description Must be exactly same-origin. */
                "Sec-Fetch-Site": components["parameters"]["ViewerFetchSite"];
                /** @description Required browser-client marker; must be exactly viewer-v1. */
                "X-XTrace-Client": components["parameters"]["ViewerClient"];
                /** @description If supplied, must exactly equal the printed viewer origin. It may be absent on browser GET requests only; Host, Sec-Fetch-Site, and X-XTrace-Client remain required. */
                Origin?: components["parameters"]["OptionalApiOrigin"];
            };
            path: {
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frame graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingGraph"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            501: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
}
