#!/bin/sh
# Generated by X-trace. X-trace never runs this file.
# operation: op-create
# route: POST /orders
# catalog state: observed
# MUTATING: POST may change state on the target. Review it before running.
# recipe 003
set -eu
: "${BASE_URL:?set BASE_URL, for example http://127.0.0.1:8080}"
curl --silent --show-error --fail-with-body -X 'POST' \
  -H 'Content-Type: application/json' \
  --data-binary '{"sku":"A-1","qty":2}' \
  "${BASE_URL}"'/orders'
