#!/bin/sh
# Generated by X-trace. X-trace never runs this file.
# operation: op-delete
# route: DELETE /orders/{id}
# catalog state: registered
# MUTATING: DELETE may change state on the target. Review it before running.
# recipe 005
set -eu
: "${BASE_URL:?set BASE_URL, for example http://127.0.0.1:8080}"
: "${XT_PATH_ID:?set XT_PATH_ID}"
curl --silent --show-error --fail-with-body --globoff --proto '=http,https' -X 'DELETE' \
  "${BASE_URL}"'/orders/'"${XT_PATH_ID}"
