#!/bin/sh
# Generated by X-trace. Run it yourself: `sh all.sh`. X-trace never does.
# Only safe-method recipes (GET/HEAD/OPTIONS) are invoked here.
# Mutating recipes are listed as comments and must be run one by one.
set -u
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
sh "$DIR/001-get-orders.sh"
sh "$DIR/002-get-orders.sh"
# not run (mutating POST): 003-post-orders.sh
sh "$DIR/004-get-orders-id.sh"
# not run (mutating DELETE): 005-delete-orders-id.sh
