#!/bin/sh
# Generated by X-trace. This file executes nothing: it prints the commands.
# Run a recipe yourself after review, for example `sh 001-...sh`.
# Mutating recipes are marked; read them before running.
set -u
printf '%s\n' 'sh 001-get-orders.sh  # GET op-list, safe method'
printf '%s\n' 'sh 002-get-orders.sh  # GET op-zdup, safe method'
printf '%s\n' 'sh 003-post-orders.sh  # POST op-create, MUTATING'
printf '%s\n' 'sh 004-get-orders-id.sh  # GET op-get-one, safe method'
printf '%s\n' 'sh 005-delete-orders-id.sh  # DELETE op-delete, MUTATING'
