//! User-data path resolution and repository pointer file.
//!
//! Slice 1A keeps durable project state under the user-data home
//! directory rather than inside the repository. The CLI resolves the
//! home directory from `XTRACE_DATA_HOME` (when set) or from the
//! platform default documented below, and writes a small
//! `.xtrace/config.toml` pointer inside the repository so subsequent
//! invocations can find the project.
//!
//! User-data home (no `XTRACE_DATA_HOME` override):
//!
//! - macOS: `$HOME/Library/Application Support/xtrace`
//! - Linux: `${XDG_DATA_HOME:-~/.local/share}/xtrace`
//! - Windows: `%APPDATA%\xtrace`
//!
//! Database path:
//!
//! ```text
//! <user_data_home>/projects/<project-id>/metadata.sqlite3
//! ```
//!
//! Repository pointer:
//!
//! ```text
//! <repo>/.xtrace/config.toml
//! ```

use std::path::{Path, PathBuf};

use xtrace_domain::ProjectId;

use crate::error::CliError;

/// Basename of the repository pointer file written by `xtrace init`.
const POINTER_BASENAME: &str = ".xtrace";
/// File name of the pointer file inside `.xtrace`.
const POINTER_FILENAME: &str = "config.toml";
/// File name of the SQLite database file inside a project directory.
const DATABASE_FILENAME: &str = "metadata.sqlite3";
/// Environment variable that overrides the user-data home directory.
const USER_DATA_HOME_ENV: &str = "XTRACE_DATA_HOME";
/// Application folder name under the user-data home.
const XTRACE_FOLDER: &str = "xtrace";
/// Subdirectory that holds one folder per project.
const PROJECTS_FOLDER: &str = "projects";

/// Pointer file written into the repository root by `xtrace init`.
///
/// The file is intentionally tiny: it contains the project identifier
/// and the absolute path of the user-data home used at init time.
/// Future slices add more fields (active policy versions, capture
/// settings, ...) without changing the file format's major version.
#[derive(Clone, Debug, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct RepositoryPointer {
    /// Pointer file format version. Bumped together with schema
    /// changes that older binaries cannot read.
    pub schema_version: u32,
    /// Stable project identifier recorded at `init` time.
    pub project_id: ProjectId,
    /// Absolute path of the user-data home directory the project
    /// lives under.
    pub data_home: PathBuf,
}

impl RepositoryPointer {
    /// Returns the relative path of the pointer file inside the
    /// repository root (`.xtrace/config.toml`). Exposed so future
    /// CLI surfaces can refer to the same constant without
    /// duplicating the layout.
    #[must_use]
    #[allow(dead_code, reason = "documentation constant; CLI uses paths:: constants directly")]
    pub fn relative_path() -> &'static str {
        ".xtrace/config.toml"
    }

    /// Writes the pointer file to the supplied repository root.
    /// The file is written atomically: the body first lands in a
    /// sibling `.tmp` file, then `rename` swaps it into place. The
    /// parent `.xtrace` directory is created with owner-only
    /// permissions when possible.
    ///
    /// # Errors
    ///
    /// Returns [`CliError::StoreUnavailable`] when the filesystem
    /// refuses the write; the file is never partially written.
    pub fn write(&self, repo: &Path) -> Result<(), CliError> {
        use std::fs;
        use std::io::Write as _;
        let pointer_dir = repo.join(POINTER_BASENAME);
        let pointer_path = pointer_dir.join(POINTER_FILENAME);
        fs::create_dir_all(&pointer_dir)
            .map_err(|err| CliError::StoreUnavailable(format!("create .xtrace: {err}")))?;
        // Render canonical TOML so hand-inspection is unambiguous.
        // The path lives on its own line because TOML string literals
        // do not support trailing backslashes; writing the path as a
        // single string is therefore sufficient and unambiguous.
        let project_id = self.project_id.to_string();
        let data_home = self.data_home.display().to_string();
        let body = format!(
            "# X-trace repository pointer.\n\
             # Auto-generated by `xtrace init`. Do not edit by hand.\n\
             schema_version = {schema}\n\
             project_id = \"{project_id}\"\n\
             data_home = \"{data_home}\"\n",
            schema = self.schema_version,
            project_id = project_id,
            data_home = data_home,
        );
        let tmp = pointer_dir.join(format!("{POINTER_FILENAME}.tmp"));
        {
            let mut file = fs::File::create(&tmp)
                .map_err(|err| CliError::StoreUnavailable(format!("create tmp pointer: {err}")))?;
            file.write_all(body.as_bytes())
                .map_err(|err| CliError::StoreUnavailable(format!("write tmp pointer: {err}")))?;
            file.sync_all()
                .map_err(|err| CliError::StoreUnavailable(format!("sync tmp pointer: {err}")))?;
        }
        fs::rename(&tmp, &pointer_path)
            .map_err(|err| CliError::StoreUnavailable(format!("rename pointer: {err}")))?;
        Ok(())
    }

    /// Reads the pointer file from the supplied repository root.
    ///
    /// # Errors
    ///
    /// Returns [`CliError::StoreCorrupted`] when the file is
    /// missing or unparseable, [`CliError::StoreUnavailable`] when
    /// the filesystem refuses the read. The CLI surfaces a missing
    /// pointer as a separate "uninitialized" error so callers can
    /// report the state truthfully.
    pub fn read(repo: &Path) -> Result<Self, CliError> {
        let pointer_path = repo.join(POINTER_BASENAME).join(POINTER_FILENAME);
        let text = std::fs::read_to_string(&pointer_path).map_err(|err| {
            if err.kind() == std::io::ErrorKind::NotFound {
                CliError::ProjectDirectoryMissing(format!(
                    "repository pointer not found: {}",
                    pointer_path.display()
                ))
            } else {
                CliError::StoreUnavailable(format!("read pointer: {err}"))
            }
        })?;
        let parsed: RepositoryPointer = toml::from_str(&text).map_err(|err| {
            CliError::StoreCorrupted(format!(
                "invalid pointer file {}: {err}",
                pointer_path.display()
            ))
        })?;
        Ok(parsed)
    }
}

/// User-data path resolver.
pub struct UserDataPaths;

impl UserDataPaths {
    /// Resolves the absolute user-data home directory, preferring the
    /// `XTRACE_DATA_HOME` environment variable. Returns
    /// [`CliError::StoreUnavailable`] when no home can be derived.
    pub fn home() -> Result<PathBuf, CliError> {
        Self::home_with(read_env_path)
    }

    /// Resolves the user-data home directory using a caller-supplied
    /// environment reader. Exposed for tests so the resolver can be
    /// exercised without mutating process-wide state.
    pub(crate) fn home_with<F>(env_reader: F) -> Result<PathBuf, CliError>
    where
        F: Fn(&str) -> Option<PathBuf>,
    {
        if let Some(value) = env_reader(USER_DATA_HOME_ENV) {
            // A relative override is ignored so a misconfigured shell
            // cannot push the store into the repository.
            if value.is_absolute() {
                return Ok(value);
            }
        }
        env_reader("HOME").and_then(|home| platform_user_data_home_from(&home)).ok_or_else(|| {
            CliError::StoreUnavailable(
                "could not determine user-data home; set XTRACE_DATA_HOME".to_string(),
            )
        })
    }

    /// Resolves the absolute directory that holds the supplied
    /// project's user-data state.
    pub fn project_dir(project_id: ProjectId) -> Result<PathBuf, CliError> {
        Ok(Self::home()?.join(PROJECTS_FOLDER).join(project_id.to_string()))
    }

    /// Resolves the absolute path of the SQLite database file for the
    /// supplied project.
    pub fn database_path(project_id: ProjectId) -> Result<PathBuf, CliError> {
        Ok(Self::project_dir(project_id)?.join(DATABASE_FILENAME))
    }
}

/// Reads an absolute path from the process environment. Returns
/// `None` when the variable is unset, empty, or not an absolute path.
pub(crate) fn read_env_path(var: &str) -> Option<PathBuf> {
    std::env::var_os(var)
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .filter(|path| path.is_absolute())
}

#[cfg(target_os = "macos")]
fn platform_user_data_home_from(home: &Path) -> Option<PathBuf> {
    Some(home.join("Library").join("Application Support").join(XTRACE_FOLDER))
}

#[cfg(target_os = "linux")]
fn platform_user_data_home_from(home: &Path) -> Option<PathBuf> {
    Some(home.join(".local").join("share").join(XTRACE_FOLDER))
}

#[cfg(target_os = "windows")]
fn platform_user_data_home_from(home: &Path) -> Option<PathBuf> {
    Some(home.join(XTRACE_FOLDER))
}

#[cfg(not(any(target_os = "macos", target_os = "linux", target_os = "windows")))]
fn platform_user_data_home_from(_home: &Path) -> Option<PathBuf> {
    None
}

#[cfg(target_os = "macos")]
#[allow(dead_code, reason = "kept for binary-level fallback if home_with is bypassed")]
fn platform_user_data_home() -> Option<PathBuf> {
    read_env_path("HOME").and_then(|home| platform_user_data_home_from(&home))
}

#[cfg(target_os = "linux")]
#[allow(dead_code, reason = "kept for binary-level fallback if home_with is bypassed")]
fn platform_user_data_home() -> Option<PathBuf> {
    if let Some(value) = read_env_path("XDG_DATA_HOME") {
        return Some(value.join(XTRACE_FOLDER));
    }
    read_env_path("HOME").and_then(|home| platform_user_data_home_from(&home))
}

#[cfg(target_os = "windows")]
#[allow(dead_code, reason = "kept for binary-level fallback if home_with is bypassed")]
fn platform_user_data_home() -> Option<PathBuf> {
    read_env_path("APPDATA").map(|path| path.join(XTRACE_FOLDER))
}

#[cfg(not(any(target_os = "macos", target_os = "linux", target_os = "windows")))]
#[allow(dead_code, reason = "kept for binary-level fallback if home_with is bypassed")]
fn platform_user_data_home() -> Option<PathBuf> {
    None
}

#[cfg(test)]
// Tests intentionally panic on invariant violations because the
// failure mode is "test failed", not "library panicked".
#[allow(clippy::unwrap_used, clippy::expect_used, reason = "tests assert on fallible fixture data")]
mod tests {
    use super::*;

    #[test]
    fn relative_path_matches_documented_layout() {
        assert_eq!(RepositoryPointer::relative_path(), ".xtrace/config.toml");
    }

    #[test]
    fn user_data_home_prefers_explicit_override() {
        let resolved = UserDataPaths::home_with(|var| {
            if var == USER_DATA_HOME_ENV {
                Some(PathBuf::from("/tmp/xtrace-data-home-test"))
            } else {
                None
            }
        })
        .expect("home resolves");
        assert_eq!(resolved, PathBuf::from("/tmp/xtrace-data-home-test"));
    }

    #[test]
    fn user_data_home_rejects_relative_env() {
        // A relative override is ignored so a misconfigured shell
        // cannot push the store into the repository.
        let resolved = UserDataPaths::home_with(|var| {
            if var == USER_DATA_HOME_ENV { Some(PathBuf::from("relative/path")) } else { None }
        });
        // The injected reader returns a relative path; the
        // implementation must discard it and fall back to the
        // platform default or error.
        if let Ok(path) = resolved {
            assert!(path.is_absolute());
        }
    }

    #[test]
    fn user_data_home_uses_platform_default() {
        // No `XTRACE_DATA_HOME`, but a `HOME` is provided so the
        // platform-default branch must produce an absolute path.
        let resolved = UserDataPaths::home_with(|var| match var {
            USER_DATA_HOME_ENV => None,
            "HOME" => Some(PathBuf::from("/tmp/fake-home")),
            _ => None,
        });
        if let Ok(path) = resolved {
            assert!(path.is_absolute());
            assert!(path.starts_with("/tmp/fake-home"));
        }
    }

    #[test]
    fn user_data_home_errors_when_unset() {
        let resolved = UserDataPaths::home_with(|_| None);
        assert!(resolved.is_err());
    }

    #[test]
    fn pointer_round_trips_through_disk() {
        let dir = tempdir();
        let repo = dir.join("repo");
        std::fs::create_dir_all(&repo).expect("repo");
        let project_id = ProjectId::new();
        let data_home = dir.join("user-data");
        std::fs::create_dir_all(&data_home).expect("user-data");
        let pointer =
            RepositoryPointer { schema_version: 1, project_id, data_home: data_home.clone() };
        pointer.write(&repo).expect("write");
        let loaded = RepositoryPointer::read(&repo).expect("read");
        assert_eq!(loaded, pointer);
    }

    #[test]
    fn read_missing_pointer_is_recoverable() {
        let dir = tempdir();
        let repo = dir.join("missing-repo");
        std::fs::create_dir_all(&repo).expect("repo");
        let err = RepositoryPointer::read(&repo).unwrap_err();
        assert!(matches!(err, CliError::ProjectDirectoryMissing(_)));
    }

    fn tempdir() -> PathBuf {
        use std::time::{SystemTime, UNIX_EPOCH};
        let nanos = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();
        let path = std::env::temp_dir().join(format!("xtrace-cli-paths-{nanos}"));
        std::fs::create_dir_all(&path).unwrap();
        path
    }
}
